"""empty message

Revision ID: 23e6d01580aa
Revises: febddcde76ff
Create Date: 2021-03-25 16:35:51.117922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23e6d01580aa'
down_revision = 'febddcde76ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notes__to__tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tags_id', sa.Integer(), nullable=True),
    sa.Column('notes_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['notes_id'], ['notes.id'], ),
    sa.ForeignKeyConstraint(['tags_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('notes_to_tags')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notes_to_tags',
    sa.Column('tags_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('notes_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['notes_id'], ['notes.id'], name='notes_to_tags_notes_id_fkey'),
    sa.ForeignKeyConstraint(['tags_id'], ['tags.id'], name='notes_to_tags_tags_id_fkey'),
    sa.PrimaryKeyConstraint('tags_id', 'notes_id', name='notes_to_tags_pkey')
    )
    op.drop_table('notes__to__tags')
    # ### end Alembic commands ###
