"""empty message

Revision ID: 741f74839bcc
Revises: 257625597eb1
Create Date: 2021-03-21 09:48:50.556447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '741f74839bcc'
down_revision = '257625597eb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('userId', sa.Integer(), nullable=True))
    op.drop_constraint('tags_user_id_fkey', 'tags', type_='foreignkey')
    op.create_foreign_key(None, 'tags', 'users', ['userId'], ['id'])
    op.drop_column('tags', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tags', type_='foreignkey')
    op.create_foreign_key('tags_user_id_fkey', 'tags', 'users', ['user_id'], ['id'])
    op.drop_column('tags', 'userId')
    # ### end Alembic commands ###
