"""grammar

Revision ID: 7893ef1bce3b
Revises: 4d31e2b78b51
Create Date: 2021-03-21 01:45:10.968359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7893ef1bce3b'
down_revision = '4d31e2b78b51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('firstName', sa.String(length=40), nullable=False))
    op.add_column('users', sa.Column('lastName', sa.String(length=40), nullable=False))
    op.drop_column('users', 'firstname')
    op.drop_column('users', 'lastname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('lastname', sa.VARCHAR(length=40), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('firstname', sa.VARCHAR(length=40), autoincrement=False, nullable=False))
    op.drop_column('users', 'lastName')
    op.drop_column('users', 'firstName')
    # ### end Alembic commands ###
