"""backref fix

Revision ID: 92438e1625e2
Revises: e8d00ba10057
Create Date: 2021-03-21 09:39:52.900910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92438e1625e2'
down_revision = 'e8d00ba10057'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstName', sa.String(length=40), nullable=False),
    sa.Column('lastName', sa.String(length=40), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('theme', sa.Boolean(), nullable=True),
    sa.Column('bgroundimg', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.drop_table('users')
    op.drop_constraint('notebooks_userId_fkey', 'notebooks', type_='foreignkey')
    op.create_foreign_key(None, 'notebooks', 'user', ['userId'], ['id'])
    op.add_column('tags', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tags', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tags', type_='foreignkey')
    op.drop_column('tags', 'user_id')
    op.drop_constraint(None, 'notebooks', type_='foreignkey')
    op.create_foreign_key('notebooks_userId_fkey', 'notebooks', 'users', ['userId'], ['id'])
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('theme', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('bgroundimg', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('firstName', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('lastName', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('email', name='users_email_key'),
    sa.UniqueConstraint('username', name='users_username_key')
    )
    op.drop_table('user')
    # ### end Alembic commands ###
